# .github/workflows/build-and-package.yml

name: Build and Package SE Application with OpenJDK 17

on:
  push:
    branches:
      - main # 或者你使用的其他分支名称
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # 使用 Temurin 分发版，这是 Eclipse Adoptium 的一部分，提供 OpenJDK 构建

    - name: Run se.jar
      run: |
        java -jar se.jar

    - name: Zip application files
      run: |
        zip -r a.zip . -x ".git/*" # 创建一个包含当前目录下所有文件（除了.git）的ZIP文件

    - name: Upload a.zip as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: se-application-zip # 制品的名字
        path: a.zip # 要上传的文件路径
